server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  path: "./log/"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
  file: "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"
  prefix: ""            # 日志内容输出前缀。默认为空
  level: "all"         # 日志输出级别
  stdout: true

#数据库配置
database:
  default:
    type:                  "mysql"
    host:                  "127.0.0.1"
    port:                  "3309"
    user:                  "jjcc"
    pass:                  "j62nusynXtijrUlb"
    name:                  "jjcc_system"
    debug:   true

# Redis配置
redis:
  default:
    address:    127.0.0.1:16380
    db:         1
    pass:       123456

  db:
    address:     127.0.0.1:16379
    db:          1
    pass:        123456