// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminRole is the golang structure of table jjcc_admin_role for DAO operations like Where/Data.
type AdminRole struct {
	g.Meta       `orm:"table:jjcc_admin_role, do:true"`
	Id           interface{} // 主键ID
	Name         interface{} // 角色名称
	Desc         interface{} // 角色说明
	CreateTime   *gtime.Time // 创建时间
	UpdateTime   *gtime.Time // 更新时间
	Status       interface{} // 是否启用：0禁用，1启用
	RoleNo       interface{} // 角色编号
	IsDefault    interface{} // 是否是默认角色
	IsAllowLogin interface{} // 是否允许登录erp后台：0否 1是
	Source       interface{} // 来源：1、erp后台 2、命令行添加
}
