// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminRole is the golang structure for table admin_role.
type AdminRole struct {
	Id           uint        `json:"id"             ` // 主键ID
	Name         string      `json:"name"           ` // 角色名称
	Desc         string      `json:"desc"           ` // 角色说明
	CreateTime   *gtime.Time `json:"create_time"    ` // 创建时间
	UpdateTime   *gtime.Time `json:"update_time"    ` // 更新时间
	Status       int         `json:"status"         ` // 是否启用：0禁用，1启用
	RoleNo       string      `json:"role_no"        ` // 角色编号
	IsDefault    int         `json:"is_default"     ` // 是否是默认角色
	IsAllowLogin int         `json:"is_allow_login" ` // 是否允许登录erp后台：0否 1是
	Source       int         `json:"source"         ` // 来源：1、erp后台 2、命令行添加
}
