// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminUser is the golang structure for table admin_user.
type AdminUser struct {
	Id             uint        `json:"id"               ` // 主键ID
	DingUserId     string      `json:"ding_user_id"     ` // 钉钉用户ID,很长，必须为varchar
	Mobile         string      `json:"mobile"           ` // 管理员账号
	Name           string      `json:"name"             ` // 管理员姓名
	Passwd         string      `json:"passwd"           ` // 登录密码
	Sex            uint        `json:"sex"              ` // 0未知 1男 2女
	BkOrgId        int         `json:"bk_org_id"        ` //
	Email          string      `json:"email"            ` // 邮箱
	Status         int         `json:"status"           ` // 状态 0：正常  1：冻结
	IsExternalUser uint        `json:"is_external_user" ` // 是否外部用户
	IsBuiltinUser  uint        `json:"is_builtin_user"  ` // 是否系统内置用户
	LastLoginTime  *gtime.Time `json:"last_login_time"  ` // 最后登录时间
	LastLoginIp    string      `json:"last_login_ip"    ` // 最后登录IP
	IsBind         int         `json:"is_bind"          ` // 是否绑定酷家乐账号：0否 1是
	JobNumber      string      `json:"job_number"       ` // 工号
	Position       string      `json:"position"         ` // 职位
	LeaderId       int         `json:"leader_id"        ` //
	EntryTime      *gtime.Time `json:"entry_time"       ` // 入职时间
	IsInit         int         `json:"is_init"          ` // 是否是初始化状态：0否 1是
	Source         int         `json:"source"           ` // 创建来源：0：erp后台  1：接口
	IsShow         int         `json:"is_show"          ` // 是否显示在后台:1显示，0否
	Avatar         string      `json:"avatar"           ` // 用户头像（暂时用于竣工调研）
	CreateTime     *gtime.Time `json:"create_time"      ` // 创建时间
	UpdateTime     *gtime.Time `json:"update_time"      ` // 最后更新时间
}
